version: "3.5"

services:

    database:
        container_name: postgresql
        image: postgres:latest
        ports:
            - "5432:5432"
        networks:
            - networkid
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: 22
            POSTGRES_USER: adityaudi
            POSTGRES_DB: coffeeshop

    cache:
        container_name: redis
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - networkid
        volumes:
            - ./redisdata:/data

networks:
    networkid:
        name: networkid
